# Generated by Django 3.1.1 on 2020-09-09 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namebook', models.CharField(max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('datereturn', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('yearRelease', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.CharField(max_length=120)),
                ('available', models.BooleanField(default=True)),
                ('isbn', models.IntegerField()),
                ('memberships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.memberships')),
            ],
        ),
    ]
