# Generated by Django 3.1.1 on 2020-09-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='memberships',
            field=models.ForeignKey(default='no one', on_delete=django.db.models.deletion.CASCADE, to='libraryapp.memberships'),
        ),
    ]
