# Generated by Django 3.1.1 on 2020-09-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20200909_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='memberships',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='libraryapp.memberships'),
        ),
    ]
